# Generated by Django 2.1.4 on 2020-02-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='posted_by',
        ),
    ]
